export const headers = {
  title: 'Title',
  datePublished: 'Date Published',
  isbn: 'ISBN',
  quantity: 'Quantity', // maybe delete
  genre: 'Genre',
  publicationItemType: "Publication Item Type",
  edition: "Edition",
  format: "Format",
  purchasePrice: "Purchase Price",
  rentalRate: "Rental Rate",
  status: "Status",
  publicationItemStatus: "Status",
  literaryType: "LiteraryType",
  issueDate: "Issue Date",
  issueNumber: "Issue Number",
  volume: "Volume",
  issueName: "Issue Name",
  accessoryName: "Accessory Name",
  accessoryType: "Accessory Type",
  price: "Price",
  itemId: "ID",
  accessoryItemStatus: "Status",
  transactionType: "Transaction Type",
  name: "Name",
  firstName: "First Name",
  lastName: "Last Name",
  totalProfit: "Total Profit",
  orderId: "Order ID",
  email: "Email",
  transactionId: "Transaction ID",
  date: "Date",
  inStock: "Total in Stock",
  itemType: "Item Type",
  totalUnitsSold: "Total Sold",
  orderTotal: "Order Total"

}
