import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://localhost:4200/accessoryform');
  await page.locator('input[type="email"]').click();
  await page.locator('input[type="email"]').fill('bfadmin');
  await page.locator('input[type="password"]').click();
  await page.locator('input[type="password"]').fill('bfadmin');
  await page.getByRole('button', { name: 'Login' }).nth(1).click();
  await page.getByRole('link', { name: 'Admin Dashboard' }).click();
  await page.getByRole('listitem').filter({ hasText: 'Add An Accessory' }).click();
  await page.getByRole('link', { name: 'Add An Accessory' }).click();
  await page.getByRole('textbox', { name: 'Accessory Name' }).click();
  await page.getByRole('textbox', { name: 'Accessory Name' }).fill('Playwright Test');
  await page.getByRole('textbox', { name: 'Accessory Name' }).press('Tab');
  await page.getByLabel('Accessory Type BookmarkMugPen').press('ArrowDown');
  await page.getByLabel('Accessory Type BookmarkMugPen').selectOption('BOOKMARK');
  await page.getByLabel('Accessory Type BookmarkMugPen').press('Tab');
  await page.getByRole('textbox', { name: 'Price' }).fill('2');
  await page.getByRole('textbox', { name: 'Price' }).press('Tab');
  await page.getByRole('textbox', { name: 'Quantity' }).fill('3');
  await page.getByRole('button', { name: 'Add Accessory' }).click();
  await expect(page.getByRole('list')).toContainText('Accessory Name: Playwright Test');
  await expect(page.getByRole('list')).toContainText('Accessory Type: BOOKMARK');
  await expect(page.getByRole('list')).toContainText('Price: 2');
  await expect(page.getByRole('list')).toContainText('Quantity: 3');
  await expect(page.locator('tbody')).toContainText('AVAILABLE');
  await page.getByRole('link', { name: 'Update Accessory' }).click();
  await page.getByRole('textbox', { name: 'Accessory Name' }).click();
  await page.getByRole('textbox', { name: 'Accessory Name' }).fill('Playwright Test updated');
  await page.getByRole('button', { name: 'Update Accessory' }).click();
  await expect(page.locator('h3')).toContainText('Playwright Test updated');
  await page.getByRole('button', { name: 'back' }).click();
  await page.getByRole('button', { name: 'back' }).click();
  await page.getByRole('button', { name: 'back' }).click();
  await page.getByRole('button', { name: 'back' }).click();
  await expect(page.locator('body')).toContainText('Playwright Test updated');
});