import { test, expect } from '@playwright/test';

test("admin creates, reads, updates, deletes publications and publicationItems", async ({ page }) => {
  await page.goto('https://localhost:4200/');
  await page.getByRole('link', { name: 'Login' }).click();
  await page.locator('input[type="email"]').click();
  await page.locator('input[type="email"]').fill('admin');
  await page.locator('input[type="email"]').press('Tab');
  await page.locator('input[type="password"]').fill('admin');
  await page.getByRole('main').getByRole('button', { name: 'Login' }).click();
  await page.locator('input[type="email"]').click();
  await page.locator('input[type="email"]').fill('bfadmin');
  await page.locator('input[type="password"]').click();
  await page.locator('input[type="password"]').fill('bfadmin');
  await page.getByRole('main').getByRole('button', { name: 'Login' }).click();
  await page.getByRole('link', { name: 'Admin Dashboard' }).click();
  await page.getByRole('link', { name: 'The Secret Treehouse Club' }).click();
  await page.getByRole('link', { name: 'Update Publication' }).click();
  await page.getByRole('textbox', { name: 'Title*' }).click();
  await page.getByRole('textbox', { name: 'Title*' }).fill('The Secret Treehouse Club2');
  await page.getByRole('button', { name: 'Submit' }).click();
  await expect(page.getByText('Publication Added.')).toBeVisible();
  await page.getByRole('button', { name: 'New Publication' }).click();
  await page.getByRole('textbox', { name: 'Title*' }).click();
  await page.getByRole('textbox', { name: 'Title*' }).fill('Playwright');
  await page.getByRole('textbox', { name: 'Title*' }).press('Tab');
  await page.getByLabel('Genre*').selectOption('COMEDY');
  await page.locator('div').filter({ hasText: /^ISBN\*$/ }).click();
  await page.getByRole('spinbutton', { name: 'ISBN*' }).fill('1234567890');
  await page.getByRole('textbox', { name: 'Publish Date*' }).fill('2025-10-08');
  await page.getByRole('textbox', { name: 'First Name*' }).click();
  await page.getByRole('textbox', { name: 'First Name*' }).fill('Play');
  await page.getByRole('textbox', { name: 'First Name*' }).press('Tab');
  await page.getByRole('textbox', { name: 'Last Name*' }).fill('Wright');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('link', { name: 'Add Items' }).click();
  await page.getByLabel('Publication Item Type*').selectOption('BOOK');
  await page.getByRole('spinbutton', { name: 'Quantity*' }).click();
  await page.getByRole('spinbutton', { name: 'Quantity*' }).fill('3');
  await page.getByRole('textbox', { name: 'Edition*' }).click();
  await page.getByRole('textbox', { name: 'Edition*' }).fill('PWE');
  await page.getByLabel('Format*').selectOption('HARDCOPY');
  await page.getByRole('spinbutton', { name: 'Purchase Price*' }).click();
  await page.getByRole('spinbutton', { name: 'Purchase Price*' }).fill('6.79');
  await page.getByRole('spinbutton', { name: 'Rental Rate*' }).click();
  await page.getByRole('spinbutton', { name: 'Rental Rate*' }).fill('2.34');
  await page.getByRole('button', { name: 'Submit' }).click();
  await expect(page.getByText('Publication Item Added.')).toBeVisible();
  await page.getByRole('link', { name: 'Edit' }).first().click();
  await page.getByLabel('Format*').selectOption('AUDIOBOOK');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('button', { name: 'delete' }).nth(3).click();
  await page.getByRole('button', { name: 'delete' }).nth(2).click();
  await page.getByRole('button', { name: 'delete', exact: true }).nth(0).click();
  await page.getByRole('button', { name: 'Delete Publication' }).click();
  await page.getByRole('link', { name: 'The Secret Treehouse Club2' }).click();
  await page.getByRole('link', { name: 'Update Publication' }).click();
  await page.getByRole('textbox', { name: 'Title*' }).click();
  await page.getByRole('textbox', { name: 'Title*' }).fill('The Secret Treehouse Club');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('link', { name: 'Admin Dashboard' }).click();
});