import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:4200/shop');
  await page.getByRole('link', { name: 'Pride and Prejudice' }).click();
  await page.getByRole('button', { name: 'Purchase' }).first().click();
  await page.getByRole('button', { name: 'Rent' }).nth(1).click();
  await page.getByRole('button', { name: 'Back' }).click();
  await page.getByRole('link', { name: 'Ceramic Mug' }).click();
  await page.getByRole('button', { name: 'Purchase' }).click();
  await page.getByRole('button', { name: 'Back' }).click();
  await page.getByRole('link', { name: 'Rollerball Pen' }).click();
  await page.getByRole('button', { name: 'Purchase' }).click();
  await page.getByRole('button', { name: 'Back' }).click();
  await page.getByRole('link', { name: 'Vintage Bookmark' }).click();
  await page.getByRole('button', { name: 'Purchase' }).click();
  await page.getByRole('button', { name: 'Checkout' }).click();
  await page.getByRole('button', { name: 'Back' }).click();
  await page.getByRole('link', { name: 'Magnetic Bookmark' }).click();
  await page.getByRole('button', { name: 'Purchase' }).click();
  await expect(page.getByRole('list')).toContainText('Quantity: 0');
  await page.getByRole('button', { name: 'Checkout' }).click();
  await expect(page.locator('tbody')).toContainText('Pride and Prejudice');
  await expect(page.locator('tbody')).toContainText('Pride and Prejudice');
  await expect(page.locator('tbody')).toContainText('Ceramic Mug');
  await expect(page.locator('tbody')).toContainText('Rollerball Pen');
  await expect(page.locator('tbody')).toContainText('Vintage Bookmark');
  await expect(page.locator('tbody')).toContainText('Magnetic Bookmark');
  await page.getByRole('textbox', { name: 'First Name' }).click();
  await page.getByRole('textbox', { name: 'First Name' }).fill('Play');
  await page.getByRole('textbox', { name: 'First Name' }).press('Tab');
  await page.getByRole('textbox', { name: 'Last Name' }).fill('Wright');
  await page.getByRole('textbox', { name: 'Last Name' }).press('Tab');
  await page.getByRole('textbox', { name: 'Street Address' }).fill('pw avenue');
  await page.getByRole('textbox', { name: 'Street Address' }).press('Tab');
  await page.getByRole('textbox', { name: 'City' }).fill('somewhere');
  await page.getByRole('textbox', { name: 'City' }).press('Tab');
  await page.getByRole('textbox', { name: 'State' }).fill('somestate');
  await page.getByRole('textbox', { name: 'State' }).press('Tab');
  await page.getByRole('spinbutton', { name: 'Zip' }).fill('12345');
  await page.getByRole('spinbutton', { name: 'Zip' }).press('Tab');
  await page.getByRole('textbox', { name: 'Country' }).fill('US');
  await page.getByRole('textbox', { name: 'Country' }).press('Tab');
  await page.getByRole('textbox', { name: 'Email' }).fill('play@wright.com');
  await page.getByRole('textbox', { name: 'Email' }).press('Tab');
  await page.getByRole('textbox', { name: 'Phone' }).fill('123456789');
  page.once('dialog', dialog => {
    console.log(`Dialog message: ${dialog.message()}`);
    dialog.dismiss().catch(() => {});
  });
  await page.getByRole('button', { name: 'Submit Order' }).click();
});