import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:4200/publicationform');
  await page.getByRole('textbox', { name: 'Title' }).click();
  await page.getByRole('textbox', { name: 'Title' }).fill('pw');
  await page.getByLabel('Genre SciFiComedyFantasyYouth').selectOption('SCIFI');
  await page.getByRole('spinbutton', { name: 'ISBN' }).click();
  await page.getByRole('spinbutton', { name: 'ISBN' }).fill('123');
  await page.getByRole('textbox', { name: 'Publish Date' }).fill('2025-09-15');
  await page.getByRole('textbox', { name: 'First Name' }).click();
  await page.getByRole('textbox', { name: 'First Name' }).fill('play');
  await page.getByRole('textbox', { name: 'First Name' }).press('Tab');
  await page.getByRole('textbox', { name: 'Last Name' }).fill('wright');
  await page.getByRole('button', { name: 'Submit' }).click();
  await expect(page.locator('publication-items')).toContainText('pw');
  await expect(page.locator('publication-items')).toContainText('Genre: SCIFI');
  await expect(page.locator('publication-items')).toContainText('Date Published: Sep 15, 2025');
  await expect(page.locator('publication-items')).toContainText('ISBN: 123');
  await expect(page.locator('publication-items')).toContainText('Quantity: 0');
  await expect(page.locator('publication-items')).toContainText('First Name: play');
  await page.getByRole('link', { name: 'Add Items' }).click();
  await page.getByRole('spinbutton', { name: 'Rental Rate' }).click();
  await page.getByLabel('Publication Item Type').selectOption('BOOK');
  await page.getByRole('spinbutton', { name: 'Quantity' }).click();
  await page.getByRole('textbox', { name: 'Edition' }).click();
  await page.getByRole('textbox', { name: 'Edition' }).fill('pwe');
  await page.getByLabel('Format AudioBookHardCopyEBook').selectOption('AUDIOBOOK');
  await page.getByRole('spinbutton', { name: 'Purchase Price' }).click();
  await page.getByRole('spinbutton', { name: 'Purchase Price' }).fill('8.99');
  await page.getByRole('spinbutton', { name: 'Rental Rate' }).click();
  await page.getByRole('spinbutton', { name: 'Rental Rate' }).fill('2.99');
  await page.getByRole('button', { name: 'Submit' }).click();
  await expect(page.getByRole('row')).toContainText('BOOK');
  await expect(page.getByRole('row')).toContainText('pwe');
  await expect(page.getByRole('row')).toContainText('8.99');
  await expect(page.getByRole('row')).toContainText('2.99');
  await expect(page.getByRole('row')).toContainText('AVAILABLE');
  await page.getByRole('link', { name: 'Update Publication' }).click();
  await page.getByRole('textbox', { name: 'Title' }).click();
  await page.getByRole('textbox', { name: 'Title' }).fill('pw updated');
  await page.getByLabel('Genre SciFiComedyFantasyYouth').selectOption('COMEDY');
  await page.getByRole('textbox', { name: 'First Name' }).click();
  await page.getByRole('textbox', { name: 'First Name' }).fill('playz');
  await page.getByRole('textbox', { name: 'Publish Date' }).fill('2025-09-17');
  await page.getByRole('button', { name: 'Submit' }).click();
  await expect(page.locator('publication-items')).toContainText('pw updated');
  await expect(page.locator('publication-items')).toContainText('Genre: COMEDY');
  await expect(page.locator('publication-items')).toContainText('Date Published: Sep 17, 2025');
  await page.getByRole('main').click();
  await page.getByRole('link', { name: 'Add Items' }).click();
  await page.getByLabel('Publication Item Type').selectOption('JOURNAL');
  await page.getByRole('spinbutton', { name: 'Quantity' }).click();
  await page.getByRole('spinbutton', { name: 'Quantity' }).click();
  await page.getByRole('spinbutton', { name: 'Quantity' }).click();
  await page.getByRole('spinbutton', { name: 'Quantity' }).click();
  await page.getByRole('spinbutton', { name: 'Quantity' }).fill('3');
  await page.getByText('Back pw updated Genre:').click();
  await page.getByRole('link', { name: 'Add Items' }).click();
  await page.getByLabel('Publication Item Type').selectOption('JOURNAL');
  await page.getByRole('spinbutton', { name: 'Quantity' }).click();
  await page.getByRole('spinbutton', { name: 'Quantity' }).click();
  await page.getByRole('spinbutton', { name: 'Quantity' }).click();
  await page.getByRole('spinbutton', { name: 'Quantity' }).click();
  await page.getByRole('spinbutton', { name: 'Quantity' }).fill('2');
  await page.getByRole('textbox', { name: 'Edition' }).click();
  await page.getByRole('textbox', { name: 'Edition' }).fill('pwe2');
  await page.getByLabel('Format AudioBookHardCopyEBook').selectOption('HARDCOPY');
  await page.getByRole('spinbutton', { name: 'Purchase Price' }).click();
  await page.getByRole('spinbutton', { name: 'Purchase Price' }).fill('9');
  await page.getByRole('spinbutton', { name: 'Rental Rate' }).click();
  await page.getByRole('spinbutton', { name: 'Rental Rate' }).fill('2');
  await page.getByRole('textbox', { name: 'Issue Date' }).fill('2025-09-17');
  await page.getByRole('spinbutton', { name: 'Issue Number' }).click();
  await page.getByRole('spinbutton', { name: 'Issue Number' }).fill('9');
  await page.getByRole('textbox', { name: 'Issue Name' }).click();
  await page.getByRole('textbox', { name: 'Issue Name' }).fill('nine');
  await page.getByRole('textbox', { name: 'Volume' }).click();
  await page.getByRole('textbox', { name: 'Volume' }).fill('pwe');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('cell', { name: 'Sep 17,' }).nth(1).click();
  await page.getByRole('cell', { name: 'pwe' }).nth(4).click();
});