import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://localhost:4200/');
  await page.getByRole('link', { name: 'Login' }).click();
  await page.locator('input[type="email"]').click();
  await page.locator('input[type="email"]').fill('bfadmin');
  await page.locator('input[type="email"]').press('Tab');
  await page.locator('input[type="password"]').fill('bfadmin');
  await page.getByRole('main').getByRole('button', { name: 'Login' }).click();
  await page.getByRole('link', { name: 'Admin Dashboard' }).click();
  await page.getByRole('link', { name: 'Add An Accessory' }).click();
  await page.getByRole('textbox', { name: 'Accessory Name*' }).click();
  await page.getByRole('textbox', { name: 'Accessory Name*' }).fill('Playwright test');
  await page.getByLabel('Accessory Type*').selectOption('BOOKMARK');
  await page.getByRole('textbox', { name: 'Price*' }).click();
  await page.getByRole('textbox', { name: 'Price*' }).fill('2.99');
  await page.getByRole('textbox', { name: 'Quantity*' }).click();
  await page.getByRole('textbox', { name: 'Quantity*' }).fill('3');
  await page.getByRole('button', { name: 'Add Accessory' }).click();
  await expect(page.getByText('Accessory Name: Playwright')).toBeVisible();
  await page.getByRole('row', { name: 'AVAILABLE delete' }).nth(0).getByRole('button').click();
  await expect(page.getByText('Accessory Item Deleted.')).toBeVisible();
  await page.getByRole('link', { name: 'Update Accessory' }).click();
  await page.getByRole('textbox', { name: 'Accessory Name*' }).click();
  await page.getByRole('textbox', { name: 'Accessory Name*' }).fill('Playwright test updated');
  await page.getByRole('button', { name: 'Update Accessory' }).click();
  await expect(page.getByText('Accessory Name: Playwright')).toBeVisible();
  await page.getByRole('link', { name: 'View All Accessories' }).click();
  await expect(page.getByRole('heading', { name: 'Accessories' })).toBeVisible();
  await page.getByRole('button', { name: 'back' }).click();
  await expect(page.getByRole('heading', { name: 'Playwright test updated' })).toBeVisible();
  await page.getByRole('row', { name: 'AVAILABLE delete' }).nth(0).getByRole('button').click();
  await page.getByRole('row', { name: 'AVAILABLE delete' }).nth(0).getByRole('button').click();
  await page.getByRole('button', { name: 'Delete Accessory' }).click();
  await expect(page.getByText('Accessory Deleted.')).toBeVisible();
  await page.getByRole('link', { name: 'Admin Dashboard' }).click();
  await page.getByRole('link', { name: 'Add A Publication' }).click();
  await page.getByRole('textbox', { name: 'Title*' }).click();
  await page.getByRole('textbox', { name: 'Title*' }).fill('Playwright Publication');
  await page.getByLabel('Genre*').selectOption('COMEDY');
  await page.getByRole('spinbutton', { name: 'ISBN*' }).click();
  await page.getByRole('spinbutton', { name: 'ISBN*' }).fill('12345678910');
  await page.getByRole('textbox', { name: 'Publish Date*' }).fill('2025-10-07');
  await page.getByRole('textbox', { name: 'First Name*' }).click();
  await page.getByRole('textbox', { name: 'First Name*' }).fill('Play');
  await page.getByRole('textbox', { name: 'First Name*' }).press('Tab');
  await page.getByRole('textbox', { name: 'Last Name*' }).fill('Wright');
  await page.getByRole('button', { name: 'Submit' }).click();
  await expect(page.getByText('Publication Added.')).toBeVisible();
  await page.getByRole('link', { name: 'View All Publications' }).click();
  await expect(page.getByRole('cell', { name: 'Playwright Publication' })).toBeVisible();
  await page.getByRole('link', { name: 'Playwright Publication' }).click();
  await page.getByRole('link', { name: 'Add Items' }).click();
  await page.getByLabel('Publication Item Type*').selectOption('BOOK');
  await page.getByRole('textbox', { name: 'Edition*' }).click();
  await page.getByRole('textbox', { name: 'Edition*' }).fill('PWE');
  await page.getByLabel('Format*').selectOption('AUDIOBOOK');
  await page.getByRole('spinbutton', { name: 'Purchase Price*' }).click();
  await page.getByRole('spinbutton', { name: 'Purchase Price*' }).fill('6.99');
  await page.getByRole('spinbutton', { name: 'Rental Rate*' }).click();
  await page.getByRole('spinbutton', { name: 'Rental Rate*' }).fill('2.49');
  await page.getByRole('button', { name: 'Submit' }).click();
  await expect(page.getByText('Publication Item Added.')).toBeVisible();
  await expect(page.getByRole('cell', { name: 'PWE' })).toBeVisible();
  await page.getByRole('link', { name: 'Edit' }).click();
  await page.getByLabel('Format*').selectOption('EBOOK');
  await page.getByRole('button', { name: 'Submit' }).click();
  await expect(page.getByRole('cell', { name: 'EBOOK' })).toBeVisible();
  await page.getByRole('button', { name: 'delete', exact: true }).click();
  await page.getByRole('button', { name: 'Delete Publication' }).click();
  await page.getByRole('button', { name: 'Admin Dashboard' }).click();
  await page.getByRole('button', { name: 'Shop' }).click();
  await page.getByRole('link', { name: 'Laugh Lines: A Satirical' }).click();
  await page.getByRole('row', { name: 'BOOK 1th Edition HARDCOPY $15' }).getByRole('button').first().click();
  await page.getByRole('link', { name: 'Shop' }).click();
  await page.getByRole('link', { name: 'Eco Mug' }).click();
  await page.getByRole('button', { name: 'Purchase' }).click();
  await expect(page.getByText('Quantity:')).toBeVisible();
  await expect(page.getByText('Total in cart:')).toBeVisible();
  await page.getByRole('link', { name: 'Checkout' }).click();
  await page.getByRole('button', { name: 'Submit Order' }).click();
  await expect(page.getByText('Please complete form before')).toBeVisible();
  await page.getByRole('textbox', { name: 'First Name*' }).click();
  await page.getByRole('textbox', { name: 'First Name*' }).fill('bfadmin');
  await page.getByRole('textbox', { name: 'First Name*' }).press('Tab');
  await page.getByRole('textbox', { name: 'Last Name*' }).fill('bfadmin');
  await page.getByRole('textbox', { name: 'Last Name*' }).press('Tab');
  await page.getByRole('textbox', { name: 'Street address*' }).fill('123 main st');
  await page.getByRole('textbox', { name: 'Street address*' }).press('Tab');
  await page.getByRole('textbox', { name: 'City*' }).fill('state');
  await page.getByRole('textbox', { name: 'City*' }).press('Tab');
  await page.getByRole('textbox', { name: 'State*' }).fill('a country');
  await page.getByRole('textbox', { name: 'State*' }).press('Tab');
  await page.getByRole('textbox', { name: 'ZipCode*' }).fill('123 ew45');
  await page.getByRole('textbox', { name: 'Country*' }).click();
  await page.getByRole('textbox', { name: 'Country*' }).fill('USA');
  await page.getByRole('textbox', { name: 'Email*' }).click();
  await page.getByRole('textbox', { name: 'Email*' }).fill('admin@mail.com');
  await page.getByRole('textbox', { name: 'Email*' }).press('Tab');
  await page.getByRole('textbox', { name: 'Phone*' }).fill('admin@mail.com');
  await page.getByRole('textbox', { name: 'Phone*' }).click();
  await page.getByRole('textbox', { name: 'Phone*' }).fill('+1 256 789 9854');
  await page.getByRole('button', { name: 'Submit Order' }).click();
  // await expect(page.getByText('Order Submitted!')).toBeVisible();
  await page.getByRole('link', { name: 'Home' }).click();
  await page.getByRole('link', { name: 'Home' }).press('ControlOrMeta+f');
  await page.locator('html').click();
  await page.getByRole('link', { name: 'Home' }).press('ControlOrMeta+f');
  await page.locator('body').press('ControlOrMeta+f');
  await page.getByRole('link', { name: 'Home' }).click();
  await page.getByRole('link', { name: 'Home' }).click();
  await page.getByRole('link', { name: 'Admin Dashboard' }).click();
  await page.getByRole('link', { name: 'View Recent Orders' }).click();
});